openapi: 3.0.0
info:
  title: Sample API
  description: A sample API to illustrate OpenAPI Generator
  version: 1.0.0
paths:
  /pet:
    get:
      summary: Get a pet
      responses:
        '200':
          description: A BIG pet 2
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
